# Generated by Django 3.2.18 on 2023-03-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoblog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='username',
        ),
    ]
