# Generated by Django 3.2.18 on 2023-03-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoblog', '0005_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
